builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  github:
    owner: tpetr
    name: homebrew-tap

  homepage: "https://github.com/tpetr/dns-https"

  commit_author:
    name: tpetr
    email: trpetr@gmail.com

  description: "Simple DNS-over-HTTPS proxy"
